### ISSUE TITLE
basenji_train.py Unexpected keyword argument

### ISSUE THREAD

**Issue by htdashti** [calico/basenji#94]
Hi, Im trying to follow the instruction (https://github.com/calico/basenji/tree/master/manuscripts/basset). when I ran the last command (basenji_train.py -k -o train_basset params_basset.json data_basset) I got the following error. Could you please help resolving the issue:

2021-10-06 11:09:13.849799: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/home/basenji/bin/basenji_train.py", line 165, in <module>
    main()
  File "/home/basenji/bin/basenji_train.py", line 119, in main
    eval_data, options.out_dir)
  File "/home/basenji/basenji/trainer.py", line 90, in __init__
    self.make_optimizer()
  File "/home/basenji/basenji/trainer.py", line 491, in make_optimizer
    global_clipnorm=global_clipnorm)
  File "/home/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow_core/python/keras/optimizer_v2/gradient_descent.py", line 84, in __init__
    super(SGD, self).__init__(name, **kwargs)
  File "/home/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 255, in __init__
    "passed to optimizer: " + str(k))
TypeError: Unexpected keyword argument passed to optimizer: global_clipnorm

**Comment by davek44** [comment]
Yea, I believe this option changed in tensorflow recently. The latest code should work with versions 2.4 and more recent

**Comment by htdashti** [comment]
Thanks! I re downloaded the basenji codes and it seems that issue has been resolved, but I got another error:
Traceback (most recent call last):
  File "/home/basenji/bin/basenji_train.py", line 165, in <module>
    main()
  File "/home/basenji/bin/basenji_train.py", line 111, in main
    seqnn_model = seqnn.SeqNN(params_model)
  File "/home/basenji/basenji/seqnn.py", line 35, in __init__
    self.build_model()
  File "/home/basenji/basenji/seqnn.py", line 125, in build_model
    current = self.build_block(current, block_params)
  File "/home/basenji/basenji/seqnn.py", line 98, in build_block
    current = block_func(current, **block_args)
  File "/home/basenji/basenji/blocks.py", line 1142, in dense_block
    if bn_gamma is None:
UnboundLocalError: local variable 'bn_gamma' referenced before assignment

**Comment by davek44** [comment]
Ah that's a bug that I introduced recently by renaming that option. Pull the latest from the master branch, and it should be fixed.

**Comment by htdashti** [comment]
Thanks! it is working
